id: ec079d05cfc84fe3a1f9418f40e0e1ba
initial_creation_type: ebook
source_metadata:
  title: དཔལ་རྟ་མགྲིན་གསང་སྒྲུབ་ཀྱི་བསྙེན་ཡིག་དངོས་གྲུབ་ཀྱི་རྒྱ་མཚོ་བཞུགས་སོ། །
  subtitle: ''
  authors:
  - སྨིན་གླིང་ཁྲི་པདྨ་འགྱུར་མེད་རྒྱ་མཚོའི་གསུང་།
  collection: ''
  publisher: Mindrolling Publications
  id: MIN-PG-03
  cover: tmp5utiz1_u.jpg
  credit: tmp3lyzq9n5.jpg
